// src/pages/Cv.jsx
import { useState } from "react";

import { Col, Spinner } from "react-bootstrap";


const Cv = () => {

    const [loaded, load] = useState(false);


    return (
        <>
            {!loaded && (
                <Col md="12" className="text-center">
                    <Spinner animation="border" className="text-center" />
                </Col>
            )}
            <iframe
                src="https://maemresen.github.io/resume/cv_mehmet_arif_emre_sen.pdf"
                title="title"
                frameBorder={(loaded) ? "1" : "0"}
                onLoad={() => load(true)}
                style={{
                    width: "100%",
                    height: "90vh",
                }}>
                Presss me: <a href="https://maemresen.github.io/resume/cv_mehmet_arif_emre_sen.pdf">Download PDF</a>
            </iframe>
        </>
    )
};

export default Cv;

// src/views/Cv.vue
<template>
  <div class="d-flex w-100 h-100 flex-column">
    <router-link
      to="/"
      class="p-3 btn text-white bg-dark d-flex align-items-center"
    >
      <span class="mx-auto">
        <i class="fas fa-chevron-left mr-2"></i>
        Home
      </span>
    </router-link>
    <iframe
      src="https://maemresen.github.io/curriculum-vitae/cv_mehmet_arif_emre_sen.pdf"
      width="100%"
      height="100%"
      frameborder="0"
    />
  </div>
</template>
